main:mplayer.c
	arm-linux-gcc mplayer.c example.c -o main  -I./include  -I./include/freetype2/ -L./lib -lfreetype -lpthread -I/home/aa123/jpeg_arm_lib/include    -L/home/aa123/jpeg_arm_lib/lib  -ljpeg
clean:
	rm -rf *.o main